### ISSUE TITLE
MNIST data

### ISSUE THREAD

**Issue by nirum** [haythamfayek/MatDL#1]
One slightly annoying thing about the CNN demo is that I don't know what format the MNIST data is in (`mnist_uint8.mat`). It would be nice if you could add either the data file itself (hosted somewhere) or a script that downloads MNIST data from the web and converts it into this mat file format.

(would just make it easier to quickly run your demo)

**Comment by haythamfayek** [comment]
Agreed. Added script to download and prepare MNIST.
